# SPDX-FileCopyrightText: 2024 Copilot Status Ring Contributors
# SPDX-License-Identifier: MIT
"""Deploy Copilot Command Ring hooks into a target repository or globally."""

from __future__ import annotations

import contextlib
import json
import os
import shlex
import sys
from pathlib import Path

# ── Hook events ────────────────────────────────────────────────────────────
_HOOK_EVENTS = (
    "sessionStart",
    "sessionEnd",
    "userPromptSubmitted",
    "preToolUse",
    "postToolUse",
    "postToolUseFailure",
    "permissionRequest",
    "subagentStart",
    "subagentStop",
    "agentStop",
    "preCompact",
    "errorOccurred",
    "notification",
)


def _build_hook_json() -> str:
    """Generate the Copilot CLI hook configuration JSON."""
    hooks: dict[str, list[dict[str, str]]] = {}
    for event in _HOOK_EVENTS:
        hooks[event] = [
            {
                "type": "command",
                "powershell": f".github/hooks/run-hook.ps1 {event}",
                "bash": f".github/hooks/run-hook.sh {event}",
            }
        ]
    return json.dumps({"version": 1, "hooks": hooks}, indent=2) + "\n"


# ── Wrapper script templates ──────────────────────────────────────────────
# stdout MUST remain empty — Copilot interprets stdout as control JSON.

_HOOK_PS1 = """\
# Copilot Command Ring — hook wrapper for Windows (PowerShell)
# Generated by: copilot-command-ring setup/deploy
# stdout MUST remain empty.

param(
    [Parameter(Mandatory=$true, Position=0)]
    [string]$EventName
)

$ErrorActionPreference = 'SilentlyContinue'

# Identify the Copilot CLI session for multi-session ring arbitration.
$cliProc = Get-CimInstance Win32_Process -Filter "ProcessId = $PID"
$env:COPILOT_RING_CLI_PID = $cliProc.ParentProcessId

# Prefer installed console script, fallback to python module
$Hook = $null
if (Get-Command 'copilot-command-ring' -ErrorAction SilentlyContinue) {
    $Hook = 'copilot-command-ring'
    $HookArgs = @('hook', $EventName)
} elseif (Get-Command 'py' -ErrorAction SilentlyContinue) {
    $Hook = 'py'
    $HookArgs = @('-3', '-m', 'copilot_command_ring.hook_main', $EventName)
} elseif (Get-Command 'python' -ErrorAction SilentlyContinue) {
    $Hook = 'python'
    $HookArgs = @('-m', 'copilot_command_ring.hook_main', $EventName)
}

if (-not $Hook) {
    exit 0
}

$output = $input | & $Hook @HookArgs 2>&1
$output | Where-Object { $_ -is [System.Management.Automation.ErrorRecord] } |
    ForEach-Object { [Console]::Error.WriteLine($_.Exception.Message) }
exit 0
"""

_HOOK_SH = """\
#!/usr/bin/env bash
# Copilot Command Ring — hook wrapper for macOS/Linux
# Generated by: copilot-command-ring setup/deploy
# stdout MUST remain empty.

set -euo pipefail

EVENT_NAME="${1:?Usage: run-hook.sh <event_name>}"

# Identify the Copilot CLI session for multi-session ring arbitration.
export COPILOT_RING_CLI_PID=$PPID

# Prefer installed console script, fallback to python module
if command -v copilot-command-ring &>/dev/null; then
    exec copilot-command-ring hook "$EVENT_NAME" 1>&2
elif command -v python3 &>/dev/null; then
    exec python3 -m copilot_command_ring.hook_main "$EVENT_NAME" 1>&2
elif command -v python &>/dev/null; then
    exec python -m copilot_command_ring.hook_main "$EVENT_NAME" 1>&2
fi

exit 0
"""

_HOOK_FILES: dict[str, str] = {
    "copilot-command-ring.json": _build_hook_json(),
    "run-hook.ps1": _HOOK_PS1,
    "run-hook.sh": _HOOK_SH,
}

# ── Global (user-level) hooks ─────────────────────────────────────────────


def _copilot_hooks_dir() -> Path:
    """Return the user-level Copilot CLI hooks directory.

    Respects the ``COPILOT_HOME`` environment variable when set;
    otherwise defaults to ``~/.copilot/hooks``.
    """
    copilot_home = os.environ.get("COPILOT_HOME")
    if copilot_home:
        return Path(copilot_home) / "hooks"
    return Path.home() / ".copilot" / "hooks"


def _build_global_hook_json(hooks_dir: Path) -> str:
    """Generate hook JSON with absolute paths to wrapper scripts.

    Unlike per-repo hooks (which use relative ``.github/hooks/`` paths),
    global hooks must use absolute paths because there is no repo root
    to resolve against.
    """
    ps1_path = str(hooks_dir / "run-hook.ps1")
    sh_path = (hooks_dir / "run-hook.sh").as_posix()
    ps1_quoted = "'" + ps1_path.replace("'", "''") + "'"
    sh_quoted = shlex.quote(sh_path)
    hooks: dict[str, list[dict[str, str]]] = {}
    for event in _HOOK_EVENTS:
        hooks[event] = [
            {
                "type": "command",
                "powershell": f"& {ps1_quoted} {event}",
                "bash": f"{sh_quoted} {event}",
            }
        ]
    return json.dumps({"version": 1, "hooks": hooks}, indent=2) + "\n"


def setup_global_hooks(
    *,
    force: bool = False,
    interactive: bool = True,
) -> bool:
    """Deploy hooks to the user-level Copilot CLI hooks directory.

    Installs hook config and wrapper scripts to ``~/.copilot/hooks/``
    (or ``$COPILOT_HOME/hooks/`` if set).  After this, Copilot CLI
    activates the ring in **every** repository — no per-repo deploy needed.

    Returns ``True`` if hooks were written.
    """
    hooks_dir = _copilot_hooks_dir()

    files: dict[str, str] = {
        "copilot-command-ring.json": _build_global_hook_json(hooks_dir),
        "run-hook.ps1": _HOOK_PS1,
        "run-hook.sh": _HOOK_SH,
    }

    existing = [name for name in files if (hooks_dir / name).exists()]
    if existing and not force:
        if interactive:
            names = ", ".join(existing)
            print(f"Hook files already exist in {hooks_dir}:", file=sys.stderr)
            print(f"  {names}", file=sys.stderr)
            answer = input("Overwrite? [y/N] ").strip().lower()
            if answer not in ("y", "yes"):
                print("Aborted.", file=sys.stderr)
                return False
        else:
            print(
                f"Hook files already exist in {hooks_dir}. "
                "Use --force to overwrite.",
                file=sys.stderr,
            )
            return False

    hooks_dir.mkdir(parents=True, exist_ok=True)

    for name, content in files.items():
        path = hooks_dir / name
        path.write_text(content, encoding="utf-8")
        if name.endswith(".sh"):
            with contextlib.suppress(OSError):
                path.chmod(path.stat().st_mode | 0o111)

    print(f"Installed global hooks to {hooks_dir}", file=sys.stderr)
    print(
        "The ring will now activate in all repositories automatically.",
        file=sys.stderr,
    )
    return True


def deploy_hooks(
    target_dir: str | Path,
    *,
    force: bool = False,
    interactive: bool = True,
) -> bool:
    """Deploy Copilot Command Ring hooks into *target_dir*.

    Creates ``<target_dir>/.github/hooks/`` and writes the hook config
    and wrapper scripts.  Returns ``True`` if hooks were written.

    Parameters
    ----------
    target_dir:
        Path to the root of the target repository.
    force:
        If ``True``, overwrite existing hook files without prompting.
    interactive:
        If ``True`` (default), prompt the user before overwriting.
        Ignored when *force* is ``True``.
    """
    target = Path(target_dir).resolve()
    hooks_dir = target / ".github" / "hooks"

    if not target.is_dir():
        print(f"Error: {target} is not a directory.", file=sys.stderr)
        return False

    # Check for existing hooks
    existing = [name for name in _HOOK_FILES if (hooks_dir / name).exists()]
    if existing and not force:
        if interactive:
            names = ", ".join(existing)
            print(f"Hook files already exist in {hooks_dir}:", file=sys.stderr)
            print(f"  {names}", file=sys.stderr)
            answer = input("Overwrite? [y/N] ").strip().lower()
            if answer not in ("y", "yes"):
                print("Aborted.", file=sys.stderr)
                return False
        else:
            print(
                f"Hook files already exist in {hooks_dir}. "
                "Use --force to overwrite.",
                file=sys.stderr,
            )
            return False

    # Create directory and write files
    hooks_dir.mkdir(parents=True, exist_ok=True)

    for name, content in _HOOK_FILES.items():
        path = hooks_dir / name
        path.write_text(content, encoding="utf-8")
        # Make shell script executable on Unix
        if name.endswith(".sh"):
            with contextlib.suppress(OSError):
                path.chmod(path.stat().st_mode | 0o111)

    print(f"Deployed hooks to {hooks_dir}", file=sys.stderr)
    print("  copilot-command-ring.json", file=sys.stderr)
    print("  run-hook.ps1", file=sys.stderr)
    print("  run-hook.sh", file=sys.stderr)
    return True
